[local] 
localhost

[mongodb]
mongodb.ramvootukuri.com

[redis]
redis.ramvootukuri.com

[mysql]
mysql.ramvootukuri.com

[rabbitmq]
rabbitmq.ramvootukuri.com

[catalogue]
catalogue.ramvootukuri.com

[user]
user.ramvootukuri.com

[cart]
cart.ramvootukuri.com

[shipping]
shipping.ramvootukuri.com

[payment]
payment.ramvootukuri.com

[frontend]
frontend.ramvootukuri.com